### ISSUE TITLE
crash when painting

### ISSUE THREAD

**Issue by anlalalu** [helloworld1/AnyMemo#488]
###### Reproduction Steps

1. click an item in list
2. tap 'more options'
3. tap 'paint'

###### Stack Trace

E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: org.liberty.android.fantastischmemodev, PID: 3856
                                                 java.lang.NullPointerException
                                                     at com.simplify.ink.InkView.drawBitmap(InkView.java:417)
                                                     at org.liberty.android.fantastischmemo.ui.PaintActivity$1.run(PaintActivity.java:64)
                                                     at android.os.Handler.handleCallback(Handler.java:733)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:136)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                     at dalvik.system.NativeStart.main(Native Method)

###### Debug info
App Version = 10.11.3

Android Version = 4.4.4

**Comment by helloworld1** [comment]
I think the library AnyMemo is currently using is not maintained anymore. We need to find an alternative drawing library.

**Comment by tingsu** [comment]
Hi @helloworld1 , thanks for coming up and maintaining this app. 

My tool also found a similar issue like this in the latest version (v.10.11.4-b200405) on an Android device 6.0. Any plan to fix this issue?

Reproducing Video:

![20200413_162920](https://user-images.githubusercontent.com/3156978/79129071-d7fcd100-7da4-11ea-8244-3b9b7a05d5ac.gif)

Stack Trace:

```
 FATAL EXCEPTION: main
 Process: org.liberty.android.fantastischmemo, PID: 5217
 java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawBitmap(android.graphics.Bitmap, float, float, android.graphics.Paint)' on a null object reference
 	at com.simplify.ink.InkView.drawBitmap(InkView.java:417)
 	at org.liberty.android.fantastischmemo.ui.PaintActivity$1.run(PaintActivity.java:64)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by hubortje** [comment]
Hey there, also having trouble with this feature.

For me, the error behaviour is not consistent: I'm running the latest version of GrapheneOS (2022113000) on a Pixel 6. Trying to paint (sidenote: maybe rename to draw?), and the app either crashes, works or throws me back to the main screen.

```
type: crash
osVersion: google/oriole/oriole:13/TP1A.221105.002/2022113000:user/release-keys
package: org.liberty.android.fantastischmemo:237
process: org.liberty.android.fantastischmemo
processUptime: 42322 + 181 ms

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Canvas.drawBitmap(android.graphics.Bitmap, float, float, android.graphics.Paint)' on a null object reference
 at com.simplify.ink.InkView.drawBitmap(InkView.java:1)
 at org.liberty.android.fantastischmemo.ui.PaintActivity$1.run(PaintActivity.java:2)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7904)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
