### ISSUE TITLE
Fatal crash - NumberFormatException from QuizLauncherDialogFragment

### ISSUE THREAD

**Issue by tingsu** [helloworld1/AnyMemo#494]
I searched the history issue list, and have not found similar issues.

The issue was found in the latest released version (v10.11.4) on a Android 6.0 device.

Crash stack

```
  FATAL EXCEPTION: main
 Process: org.liberty.android.fantastischmemo, PID: 3589
 java.lang.NumberFormatException: Invalid int: ""
 	at java.lang.Integer.invalidInt(Integer.java:138)
 	at java.lang.Integer.parseInt(Integer.java:358)
 	at java.lang.Integer.parseInt(Integer.java:334)
 	at org.liberty.android.fantastischmemo.ui.QuizLauncherDialogFragment$2.onClick(QuizLauncherDialogFragment.java:242)
 	at android.view.View.performClick(View.java:5198)
 	at android.view.View$PerformClick.run(View.java:21147)
 	at android.os.Handler.handleCallback(Handler.java:739)
 	at android.os.Handler.dispatchMessage(Handler.java:95)
 	at android.os.Looper.loop(Looper.java:148)
 	at android.app.ActivityThread.main(ActivityThread.java:5417)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by helloworld1** [comment]
The data is not validated for some of the inputs. empty input should be prevented.
