### ISSUE TITLE
Exception when starting activity org.liberty.android.fantastischmemo/.downloader.quizlet.QuizletLauncher

### ISSUE THREAD

**Issue by geniuslittleteddy** [helloworld1/AnyMemo#500]
![Screen Shot 2020-08-05 at 7 54 42 PM](https://user-images.githubusercontent.com/67744580/89410564-895db300-d756-11ea-9178-075563587e17.png)

```
2020-08-05 20:00:26.396 1515-3285/system_process W/ActivityManager: Exception when starting activity org.liberty.android.fantastischmemo/.downloader.quizlet.QuizletLauncher
    android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:883)
        at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1296)
        at com.android.server.am.ActivityStackSupervisor.startSpecificActivityLocked(ActivityStackSupervisor.java:1395)
        at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2514)
        at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2106)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1820)
        at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1810)
        at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1183)
        at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3483)
        at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3319)
        at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1842)
        at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
        at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:481)
        at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:357)
        at com.android.server.am.AppErrors.crashApplication(AppErrors.java:309)
        at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13308)
        at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

**Comment by helloworld1** [comment]
Quizlet was removed in the latest build since Quizlet does not allow third party to use their API anymore. They only allow their own app to use.
