### ISSUE TITLE
the app throw a org.apache.harmony.xml.ExpatParser$ParseException when converting a enpty xml file

### ISSUE THREAD

**Issue by androidAppGuard** [helloworld1/AnyMemo#525]
**We found a exception when testing the app, and the environment is as follows:**
```
App version: 10.11.3
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce (the content in a.xml is empty):**
![9_AnyMemo_ExpatParser$ParseException.gif](https://s2.loli.net/2022/05/12/dPnkFc8bHAKzCIr.gif)
**The exception log is as follows:**
```
05-12 12:54:59.191 15058-15078/org.liberty.android.fantastischmemodev E/ConvertIntentService: Error while converting
    org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: no element found
        at org.apache.harmony.xml.ExpatParser.finish(ExpatParser.java:545)
        at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:475)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
        at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
        at org.liberty.android.fantastischmemo.converter.MnemosyneXMLImporter.convert(MnemosyneXMLImporter.java:79)
        at org.liberty.android.fantastischmemo.service.ConvertIntentService.onHandleIntent(ConvertIntentService.java:101)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by jiqili** [comment]
I performed the event sequence and the app occurs the same exception, it seems the program does not consider the other file types.
